INSERT INTO MOTIVOS_CONTACTO VALUES ('Agradecimientos');
INSERT INTO MOTIVOS_CONTACTO VALUES ('Reclamos');
INSERT INTO MOTIVOS_CONTACTO VALUES ('Preguntas');
INSERT INTO MOTIVOS_CONTACTO VALUES ('Pedidos');

INSERT INTO CATEG_CONTACTO VALUES ('Prestadores');
INSERT INTO CATEG_CONTACTO VALUES ('Personal Oficina');
INSERT INTO CATEG_CONTACTO VALUES ('Medicos');

INSERT INTO MOTIVO_CATEGORIA VALUES (1,1,'MAIL_1-1@MAIL.COM');
INSERT INTO MOTIVO_CATEGORIA VALUES (1,2,'MAIL_1-2@MAIL.COM');
INSERT INTO MOTIVO_CATEGORIA VALUES (1,3,'MAIL_1-3@MAIL.COM');
INSERT INTO MOTIVO_CATEGORIA VALUES (2,1,'MAIL_2-1@MAIL.COM');
INSERT INTO MOTIVO_CATEGORIA VALUES (2,2,'MAIL_2-2@MAIL.COM');
INSERT INTO MOTIVO_CATEGORIA VALUES (2,3,'MAIL_2-3@MAIL.COM');
INSERT INTO MOTIVO_CATEGORIA VALUES (4,1,'MAIL_4-1@MAIL.COM');