INSERT INTO MOTIVOS VALUES ('Agradecimientos');
INSERT INTO MOTIVOS VALUES ('Reclamos');
INSERT INTO MOTIVOS VALUES ('Preguntas');
INSERT INTO MOTIVOS VALUES ('Pedidos');

INSERT INTO CATEGORIAS VALUES ('Prestadores');
INSERT INTO CATEGORIAS VALUES ('Personal Oficina');
INSERT INTO CATEGORIAS VALUES ('Medicos');

INSERT INTO MOTIVOS_CATEGORIAS VALUES (1,1,'MAIL_1-1@MAIL.COM');
INSERT INTO MOTIVOS_CATEGORIAS VALUES (1,2,'MAIL_1-2@MAIL.COM');
INSERT INTO MOTIVOS_CATEGORIAS VALUES (1,3,'MAIL_1-3@MAIL.COM');
INSERT INTO MOTIVOS_CATEGORIAS VALUES (2,1,'MAIL_2-1@MAIL.COM');
INSERT INTO MOTIVOS_CATEGORIAS VALUES (2,2,'MAIL_2-2@MAIL.COM');
INSERT INTO MOTIVOS_CATEGORIAS VALUES (2,3,'MAIL_2-3@MAIL.COM');
INSERT INTO MOTIVOS_CATEGORIAS VALUES (4,1,'MAIL_4-1@MAIL.COM');