CREATE TABLE TESTPERSONA (
    ID					int				NOT NULL	IDENTITY	PRIMARY KEY,
	NOMBRE				varchar(255),
    APELLIDO			varchar(255)	NOT NULL,
    DIRECCION			varchar(255),
    CIUDAD				varchar(255),
	FECHANACIMIENTO		date,
	NROCLIENTE			int
);

CREATE TABLE PROFESORES (
    IDPROFESOR			int				NOT NULL	IDENTITY	PRIMARY KEY,
	NOMBRE				varchar(255)	NOT NULL,
    APELLIDO			varchar(255)	NOT NULL,
    DIRECCION			varchar(255),
    CIUDAD				varchar(255),
);

CREATE TABLE CURSOS (
    IDCURSO				int				NOT NULL	IDENTITY	PRIMARY KEY,
    CURSO				varchar(255)	NOT NULL,
);

CREATE TABLE PROFESORESCURSOS (
    IDPROFESOR			int		NOT NULL	FOREIGN KEY REFERENCES PROFESORES(IDPROFESOR),
    IDCURSO				int		NOT NULL	FOREIGN KEY REFERENCES CURSOS(IDCURSO),
	PRIMARY KEY (IDPROFESOR,IDCURSO)
);


