CREATE TABLE MOTIVOS_CONTACTO (
    IDMOTIVO			int				NOT NULL	IDENTITY	PRIMARY KEY,
	ETIQUETA			varchar(255)	NOT NULL,
);

CREATE TABLE CATEG_CONTACTO (
    IDCATEG				int				NOT NULL	IDENTITY	PRIMARY KEY,
    ETIQUETA			varchar(255)	NOT NULL
);

CREATE TABLE MOTIVO_CATEGORIA (
	IDMOTCAT			int				NOT NULL	IDENTITY	PRIMARY KEY,
    IDMOTIVO			int				NOT NULL	FOREIGN KEY REFERENCES MOTIVOS_CONTACTO(IDMOTIVO),
    IDCATEG				int				NOT NULL	FOREIGN KEY REFERENCES CATEG_CONTACTO(IDCATEG),
	CORREO				varchar(255)	NOT NULL
);

CREATE SEQUENCE contacto_seq
  AS INT                  -- DATA TIPE
  START WITH 1            -- EMPIEZA EN 1
  INCREMENT BY 1          -- SE INCREMENTA DE A 1
  MINVALUE 1              -- VALOR MINIMO 1
  MAXVALUE 999999         -- VALOR MAXIMO 999999
  CYCLE;                  -- CUANDO LLEGA AL NUMERO MAXIMO SE REINICIA LA SEQUENCIA
  
CREATE TABLE CONTACTOS (
    ID_CONTACTO			int				NOT NULL	IDENTITY	PRIMARY KEY,
	ID_TRAMITE			varchar(14)		NOT NULL,
	ID_AFILIADO			varchar(30)		NOT NULL,
	ID_MOTIVO			int				NOT NULL,
	ID_CATEG			int,
	NOMBRE_COMPLETO     varchar(330)	NOT NULL,
	COMENTARIO			varchar(330)	NOT NULL,
	FECHA_CREACION		date            NOT NULL,
	CORREO				varchar(255)	NOT NULL,
);