/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2019-05-14 23:22:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<footer id=\"footer\">\n");
      out.write("    <section id=\"beneficios\">\n");
      out.write("        <h2 class=\"title-section\">\n");
      out.write("            <span class=\"bg-primary text\">BENEFICIOS</span>\n");
      out.write("            <span class=\"line-div\"></span>\n");
      out.write("        </h2>\n");
      out.write("        <div class=\"container text-center\">\n");
      out.write("            <ul class=\"list-unstyled list-inline row\">\n");
      out.write("                <li class=\"list-inline-item col\">\n");
      out.write("                    <img src=\"/OSDEPYM/resources/core/img/icons-01.svg\" class=\"d-none d-md-block\" alt=\"Precios accesibles\">\n");
      out.write("                    <div class=\"d-md-none\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-3 text-center\">\n");
      out.write("                                <img src=\"/OSDEPYM/resources/core/img/icons-mobile-01.svg\" alt=\"Precios accesibles\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-9 text-left\">\n");
      out.write("                                <span class=\"text\">Precios accesibles</span>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-inline-item col\">\n");
      out.write("                    <img src=\"/OSDEPYM/resources/core/img/icons-02.svg\" class=\"d-none d-md-block\" alt=\"Planes y Cobertura\">\n");
      out.write("                    <div class=\"d-md-none\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-3 text-center\">\n");
      out.write("                                <img src=\"/OSDEPYM/resources/core/img/icons-mobile-02.svg\" alt=\"Planes y Cobertura\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-9 text-left\">\n");
      out.write("                                <span class=\"text\">Planes y Cobertura</span>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-inline-item col\">\n");
      out.write("                    <img src=\"/OSDEPYM/resources/core/img/icons-03.svg\" class=\"d-none d-md-block\" alt=\"Más de 6500 prestadores\">\n");
      out.write("                    <div class=\"d-md-none\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-3 text-center\">\n");
      out.write("                                <img src=\"/OSDEPYM/resources/core/img/icons-mobile-03.svg\" alt=\"Más de 6500 prestadores\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-9 text-left\">\n");
      out.write("                                <span class=\"text\">Más de 6500 prestadores</span>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-inline-item col\">\n");
      out.write("                    <img src=\"/OSDEPYM/resources/core/img/icons-04.svg\" class=\"d-none d-md-block\" alt=\"Presencia en todo el país\">\n");
      out.write("                    <div class=\"d-md-none\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-3 text-center\">\n");
      out.write("                                <img src=\"/OSDEPYM/resources/core/img/icons-mobile-04.svg\" alt=\"Presencia en todo el país\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-9 text-left\">\n");
      out.write("                                <span class=\"text\">Presencia en todo el país</span>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-inline-item col\">\n");
      out.write("                    <img src=\"/OSDEPYM/resources/core/img/icons-05.svg\" class=\"d-none d-md-block\" alt=\"Asistencia al viajero\">\n");
      out.write("                    <div class=\"d-md-none\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-3 text-center\">\n");
      out.write("                                <img src=\"/OSDEPYM/resources/core/img/icons-mobile-05.svg\" alt=\"Asistencia al viajero\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-9 text-left\">\n");
      out.write("                                <span class=\"text\">Asistencia al viajero</span>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <div class=\"bg-gradient\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row row-footer\">\n");
      out.write("                <div class=\"col\"><img class=\"logo-footer\" src=\"/OSDEPYM/resources/core/img/logo-white.svg\" alt=\"OSDEPYM\"></div>\n");
      out.write("                <div class=\"col col-address\">\n");
      out.write("                    <p>Reconquista 458 / 2do piso\n");
      out.write("                        <br> Buenos Aires / Argentina\n");
      out.write("                        <br> Tel.: (011) 5288-5600</p>\n");
      out.write("                    <p class=\"small legal d-none d-md-block\">\n");
      out.write("                        Superintendencia de servicios de salud\n");
      out.write("                        <br> 0800-222-72583 / <a href=\"http://www.sssalud.gob.ar\">www.sssalud.gob.ar</a>\n");
      out.write("                        <br> R.N.O.S.: 4-0170-4 / R.N.E.M.P.: 1486\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col col-nosotros\">\n");
      out.write("                    <h5 class=\"title\">NOSOTROS</h5>\n");
      out.write("                    <ul class=\"list-unstyled\">\n");
      out.write("                        <li><a href=\"/autoridades.html\">Autoridades</a></li>\n");
      out.write("                        <li><a href=\"/recursos-humanos.html\">Recursos Humanos</a></li>\n");
      out.write("                        <li><a href=\"/responsabilidad-social.html\">Responsabilidad Social</a></li>\n");
      out.write("                        <li><a href=\"/telefonos-utiles.html\">Teléfonos útiles</a></li>\n");
      out.write("                        <li><a href=\"/contacto.html\">Contacto</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col col-planes\">\n");
      out.write("                    <h5 class=\"title\">NUESTROS PLANES</h5>\n");
      out.write("                    <ul class=\"list-unstyled\">\n");
      out.write("                        <li><a href=\"/P800\">P800</a></li>\n");
      out.write("                        <li><a href=\"/P3000\">P3000</a></li>\n");
      out.write("                        <li><a href=\"/P4000\">P4000</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col col-last\">\n");
      out.write("                    <h5 class=\"title\"><a href=\"/sucursales.html\">SUCURSALES</a></h5>\n");
      out.write("                    <br>\n");
      out.write("                    <h5 class=\"title\"><a href=\"/cartilla-medica.html\">CARTILLA</a></h5>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <p class=\"small legal d-none d-block d-md-block d-lg-none\">\n");
      out.write("                Superintendencia de servicios de salud\n");
      out.write("                <br> 0800-222-72583 / <a href=\"http://www.sssalud.gob.ar\">www.sssalud.gob.ar</a>\n");
      out.write("                <br> R.N.O.S.: 4-0170-4 / R.N.E.M.P.: 1486\n");
      out.write("            </p>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</footer>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
