/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2019-05-16 15:47:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.20.RELEASE.jar", Long.valueOf(1555371285627L));
    _jspx_dependants.put("jar:file:/C:/Users/PC/Documents/PiTu%5E%5E/Laburo/VAS/Proyectos/OSDEPYM/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/OSDEPYM/WEB-INF/lib/spring-webmvc-4.3.20.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1539602956000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\t<!-- Required meta tags -->\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("\n");
      out.write("\t<!-- JS -->\n");
      out.write("\t<script src=\"/OSDEPYM/resources/core/js/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"/OSDEPYM/resources/core/js/popper.min.js\"></script>\n");
      out.write("\t<script src=\"/OSDEPYM/resources/core/js/bootstrap.min.js\"></script>\n");
      out.write("    \n");
      out.write("    <script src=\"/OSDEPYM/resources/core/js/main.js\"></script>\n");
      out.write("\t<script src=\"/OSDEPYM/resources/core/js/contacto.js\"></script>\n");
      out.write("\t<script src=\"/OSDEPYM/resources/core/js/autorizacion.js\"></script>\n");
      out.write("    <script src=\"/OSDEPYM/resources/core/js/autorizacion_steps.js\"></script>\n");
      out.write("\t<script src=\"/OSDEPYM/resources/core/js/autorizacion_upload_file.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- CSS -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.6.3/css/all.css\">\n");
      out.write("    \n");
      out.write("    <link rel=\"stylesheet\" href=\"/OSDEPYM/resources/core/css/bootstrap.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/OSDEPYM/resources/core/css/fonts.css\">    \n");
      out.write("    <link rel=\"stylesheet\" href=\"/OSDEPYM/resources/core/css/main.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/OSDEPYM/resources/core/css/plan.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"/OSDEPYM/resources/core/css/reglamento.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"/OSDEPYM/resources/core/css/autorizacion_upload_file.css\">\n");
      out.write("        \n");
      out.write("    <!-- Favicon -->\n");
      out.write("    <link href=\"data:image/x-icon;base64,AAABAAEAEBAAAAAAAABoBQAAFgAAACgAAAAQAAAAIAAAAAEACAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\" rel=\"icon\" type=\"image/x-icon\" />\n");
      out.write("    \n");
      out.write("    <title>OSDEPYM</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<header id=\"header\">\n");
      out.write("    <div class=\"top bg-gradient\">\n");
      out.write("        <nav class=\"navbar-top\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <ul class=\"list-inline list-unstyled mb-0 d-inline-block\">\n");
      out.write("                \n");
      out.write("                   <li class=\"list-inline-item dropdown\">\n");
      out.write("                        <a href=\"#\" class=\"text-white\">Facturación</a>\n");
      out.write("                        <div class=\"dropdown-menu\" id=\"menuFacturacion\" style=\"z-index: 10000;\">\n");
      out.write("                            <a style=\"color: #032114;\" class=\"dropdown-item\" target=\"blank\" href=\"http://www.osdepym.com.ar/OSDEPYM_CtaCte_FE/\">Consulta y descarga de Facturas</a>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                \n");
      out.write("                \n");
      out.write("                    <li class=\"list-inline-item dropdown\">\n");
      out.write("                        <a href=\"#\" class=\"text-white\">Afiliados</a>\n");
      out.write("                        <ul class=\"dropdown-menu dropdown-menu-right\" role=\"menu\" aria-labelledby=\"dropdownMenu\" style=\"z-index: 10000;\">\n");
      out.write("                        \t<li class=\"dropdown-submenu dropdown-menu-right\">\n");
      out.write("                                <a style=\"color: #032114;\" class=\"dropdown-item\" tabindex=\"-1\" href=\"#\">Tr&aacute;mites Online</a>\n");
      out.write("                            \n");
      out.write("\t\t                        <ul class=\"dropdown-menu dropdown-menu-right\" role=\"menu\" aria-labelledby=\"dropdownMenu\">\n");
      out.write("\t\t                            <li><a style=\"color: #032114;\" class=\"dropdown-item\" href=\"/OSDEPYM/contacto/1234567890/Nombre Afiliado Test\">Canal de contacto</a></li>\n");
      out.write("\t\t                            <li class=\"dropdown-submenu dropdown-menu-right\">\n");
      out.write("\t\t                                <a style=\"color: #032114;\" class=\"dropdown-item\" tabindex=\"-1\" href=\"#\">Mi plan web</a>\n");
      out.write("\t\t                                <ul class=\"dropdown-menu dropdown-menu dropdown-menu-right\">\n");
      out.write("\t\t                                    <li><a style=\"color: #032114;\" class=\"dropdown-item\" tabindex=\"-1\" href=\"/OSDEPYM/plan/1\">Condiciones del plan</a></li>\n");
      out.write("\t\t                                    <li><a style=\"color: #032114;\" class=\"dropdown-item\" tabindex=\"-1\" href=\"/OSDEPYM/reglamento/monotributista\">Reglamento</a></li>\n");
      out.write("\t\t                                </ul>\n");
      out.write("\t\t                            </li> \n");
      out.write("\t\t                            <li><a style=\"color: #032114;\" class=\"dropdown-item\" href=\"/OSDEPYM/autorizacion/1\">Autorizacion</a></li>\n");
      out.write("\t\t                        </ul>\n");
      out.write("\t\t                   </li>\n");
      out.write("\t\t                </ul>\n");
      out.write("\t\t            </li>\n");
      out.write("                    <li class=\"list-inline-item dropdown\">\n");
      out.write("                        <a href=\"#\" target=\"blank\" class=\"text-white\">Prestadores</a>\n");
      out.write("                        <div class=\"dropdown-menu\" style=\"z-index: 10000\">\n");
      out.write("                            <a style=\"color: #032114;\" class=\"dropdown-item\" target=\"blank\" href=\"http://www.osdepym.com.ar/cas/login?service=http://www.osdepym.com.ar/prestadores-web/shiro-cas&amp;customViewParam=prestadorWeb\">Validación Online</a><a style=\"color: #032114;\" class=\"dropdown-item\" target=\"blank\" href=\" http://www.osdepym.com.ar/facturas-web/discapacidad/precargaFacturas.action\">Discapacidad</a>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"list-inline-item dropdown\">\n");
      out.write("                        <a href=\"#\" target=\"blank\" class=\"text-white\">Informes</a>\n");
      out.write("                        <div class=\"dropdown-menu\" id=\"menuDerivacion\" style=\"z-index: 10000\">\n");
      out.write("                            <a style=\"color: #032114;\" class=\"dropdown-item\" target=\"blank\" href=\"http://www.osdepym.com.ar/osdepym/main?l_event=/index_emp.htm\">Empresas</a><a style=\"color: #032114;\" class=\"dropdown-item\" target=\"blank\" href=\"http://www.osdepym.com.ar/osdepym/main?l_event=/index_ctr.htm\">Centros Médicos</a>\n");
      out.write("                            <!--<a class=\"dropdown-item\" target=\"blank\" href=\"http://www.osdepym.com.ar/osdepym/main?l_event=/index_emp.htm\">Empresas</a>\n");
      out.write("                            <a class=\"dropdown-item\" target=\"blank\" href=\"http://www.osdepym.com.ar/osdepym/main?l_event=/index_ctr.htm\">Centros médicos</a>-->\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("                <ul class=\"social-nav list-inline list-unstyled ml-auto my-0 mt-lg-0 d-inline-block d-lg-none\">\n");
      out.write("                    <li class=\"nav-item nav-item-social facebook\">\n");
      out.write("                        <a class=\"nav-link\" target=\"blank\" href=\"https://www.facebook.com/laobrasocialempresaria/\"> <span class=\"square\"><i class=\"fab fa-facebook-f\"></i> <span class=\"sr-only\">Facebook</span></span> </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item nav-item-social twitter\">\n");
      out.write("                        <a class=\"nav-link\" target=\"blank\" href=\"https://twitter.com/osdepym?lang=es\"> <span class=\"square\"><i class=\"fab fa-twitter\"></i> <span class=\"sr-only\">Twitter</span></span> </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item nav-item-social instagram\">\n");
      out.write("                        <a class=\"nav-link\" target=\"blank\" href=\"https://www.instagram.com/osdepym/\"> <span class=\"square\"><i class=\"fab fa-instagram\"></i> <span class=\"sr-only\">Instagram</span></span> </a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"mainnav\">\n");
      out.write("      <nav class=\"navbar sticky-top navbar-expand-lg navbar-light bg-light\" style=\"z-index: 12\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("              <a class=\"navbar-brand\" href=\"/OSDEPYM\"><img src=\"/OSDEPYM/resources/core/img/logo.svg\" alt=\"OSDEPYM\"></a>\n");
      out.write("              <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarTogglerDemo02\" aria-controls=\"navbarTogglerDemo02\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("                      <i class=\"fas fa-bars\"></i>\n");
      out.write("              </button>\n");
      out.write("\n");
      out.write("              <div class=\"collapse navbar-collapse\" id=\"navbarTogglerDemo02\">\n");
      out.write("              <ul class=\"navbar-nav ml-auto mt-2 mt-lg-0 text-right\">\n");
      out.write("\n");
      out.write("                  <li class=\"nav-item dropdown active\" id=\"liNosotros\">\n");
      out.write("                      <a class=\"nav-link dropdown\" href=\"javascript:NavigateTo('nosotros.htm');\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\" onmouseover=\"jQuery('#menuNosotros').show();\">\n");
      out.write("                      Nosotros\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"dropdown-menu\" id=\"menuNosotros\" aria-labelledby=\"navbarDropdown\" style=\"\">\n");
      out.write("                      \n");
      out.write("                      <a style=\"color: #032114;\" class=\"dropdown-item\" href=\"javascript:NavigateTo('internalPage.htm?idPage=1');\">Autoridades</a><a style=\"color: #032114;\" class=\"dropdown-item\" href=\"javascript:NavigateTo('internalPage.htm?idPage=2');\">Recursos Humanos</a><a style=\"color: #032114;\" class=\"dropdown-item\" href=\"javascript:NavigateTo('internalPage.htm?idPage=4');\">Teléfonos Útiles</a><a style=\"color: #032114;\" class=\"dropdown-item\" target=\"blank\" href=\"http://www.osdepym.com.ar/PortalCMS/app.htm?page=contacto\">Contacto</a>\n");
      out.write("                      \n");
      out.write("                      <!--<a class=\"dropdown-item\" href=\"javascript:NavigateTo('internalPage.htm?idPage=1');\">Autoridades</a>\n");
      out.write("                      <a class=\"dropdown-item\" href=\"javascript:NavigateTo('internalPage.htm?idPage=2');\">Recursos Humanos</a>\n");
      out.write("                      <a class=\"dropdown-item\" href=\"javascript:NavigateTo('internalPage.htm?idPage=3');\">Responsabilidad Social</a>\n");
      out.write("                      <a class=\"dropdown-item\" href=\"javascript:NavigateTo('internalPage.htm?idPage=4');\">Teléfonos útiles</a>\n");
      out.write("                      <a class=\"dropdown-item\" href=\"javascript:NavigateTo('contacto.htm');\">Contacto</a>-->\n");
      out.write("                  </div>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"nav-item\">\n");
      out.write("                  <a class=\"nav-link\" href=\"./app.htm?page=planesHome\">Planes</a>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"nav-item\">\n");
      out.write("                  <a class=\"nav-link\" href=\"./app.htm?page=sucursales\">Sucursales</a>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"nav-item\">\n");
      out.write("                  <a class=\"nav-link\" id=\"cmdCartilla\" href=\"./app.htm?page=servicios\">Cartilla</a>\n");
      out.write("                  </li>\n");
      out.write("              </ul>\n");
      out.write("              <ul class=\"navbar-nav list-inline list-unstyled social-nav ml-0 mt-2 mt-lg-0 text-right d-none d-md-inline-block\">\n");
      out.write("                  <li class=\"nav-item nav-item-social facebook\">\n");
      out.write("                      <a class=\"nav-link\" target=\"blank\" href=\"https://www.facebook.com/laobrasocialempresaria/\"> <span class=\"square\"><i class=\"fab fa-facebook-f\"></i> <span class=\"sr-only\">Facebook</span></span> </a>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"nav-item nav-item-social twitter\">\n");
      out.write("                      <a class=\"nav-link\" target=\"blank\" href=\"https://twitter.com/osdepym?lang=es\"> <span class=\"square\"><i class=\"fab fa-twitter\"></i> <span class=\"sr-only\">Twitter</span></span> </a>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"nav-item nav-item-social instagram\">\n");
      out.write("                      <a class=\"nav-link\" target=\"blank\" href=\"https://www.instagram.com/osdepym/\"> <span class=\"square\"><i class=\"fab fa-instagram\"></i> <span class=\"sr-only\">Instagram</span></span> </a>\n");
      out.write("                  </li>\n");
      out.write("              </ul>\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("        </nav>\n");
      out.write("  </div>\n");
      out.write("</header>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
